kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
spec:
  containers:
    - name: debugger
      image: tylerjbean/debug-pod
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Never
